name: "dbt2looker action"
description: "Generate lookml from dbt models"

inputs:
  tag:
    description: "dbt tag"
    required: false
  targetDir:
    description: "input target dir"
    required: false
  outputDir:
    description: "output dir"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
